# Generated by Django 2.0.7 on 2018-08-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_event_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
