# Generated by Django 2.0.7 on 2018-08-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0003_event_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='position',
            field=models.IntegerField(),
        ),
    ]
