# Generated by Django 2.0.7 on 2018-08-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0004_auto_20180805_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='main_event',
            field=models.BooleanField(default=False),
        ),
    ]
