# Generated by Django 2.0.7 on 2018-08-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0005_event_main_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
