# Generated by Django 2.0.7 on 2018-08-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0006_gallerystyle'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryStyleAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='MainGalleryAdmin', editable=False, max_length=120, null=True)),
                ('show_gallery', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='GalleryStyle',
        ),
    ]
