# Generated by Django 2.0.7 on 2018-08-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0007_auto_20180810_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerystyleadmin',
            name='show_gallery',
        ),
        migrations.AddField(
            model_name='gallerystyleadmin',
            name='gallery_active',
            field=models.BooleanField(default=True),
        ),
    ]
