# Generated by Django 2.0.7 on 2018-09-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0009_auto_20180810_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerystyleadmin',
            name='gallery_bg_color',
            field=models.CharField(default='808080', max_length=120),
        ),
    ]
