# Generated by Django 2.0.7 on 2018-09-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0010_gallerystyleadmin_gallery_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title_color',
            field=models.CharField(default='ffffff', max_length=120),
        ),
    ]
