# Generated by Django 2.0.7 on 2018-09-04 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0011_event_title_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title_color',
            new_name='event_title_color',
        ),
    ]
