# Generated by Django 2.0.7 on 2018-07-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=120, null=True)),
                ('video_active', models.BooleanField()),
                ('controls_on', models.BooleanField()),
                ('text', models.CharField(blank=True, max_length=160, null=True)),
            ],
        ),
    ]
