# Generated by Django 2.0.7 on 2018-07-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='VideoAdmin',
        ),
    ]
