# Generated by Django 2.0.7 on 2018-07-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0002_auto_20180724_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoadmin',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
