# Generated by Django 2.0.7 on 2018-07-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0003_auto_20180724_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoadmin',
            name='text',
        ),
        migrations.AlterField(
            model_name='videoadmin',
            name='name',
            field=models.CharField(editable=False, max_length=120, null=True),
        ),
    ]
