# Generated by Django 2.0.7 on 2018-07-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0004_auto_20180724_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=120, null=True)),
                ('slider_active', models.BooleanField()),
                ('controls_on', models.BooleanField()),
                ('text', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
