# Generated by Django 2.0.7 on 2018-07-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0005_slideradmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideradmin',
            name='text',
        ),
        migrations.AddField(
            model_name='slideradmin',
            name='number_imgs',
            field=models.IntegerField(null=True),
        ),
    ]
