# Generated by Django 2.0.7 on 2018-07-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0006_auto_20180724_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideradmin',
            name='number_imgs',
            field=models.IntegerField(default=3),
        ),
    ]
