# Generated by Django 2.0.7 on 2018-07-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0009_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slideradmin',
            options={'verbose_name_plural': 'Slider Admin'},
        ),
        migrations.AlterModelOptions(
            name='videoadmin',
            options={'verbose_name_plural': 'Video Admin'},
        ),
        migrations.RemoveField(
            model_name='slideradmin',
            name='number_imgs',
        ),
    ]
