# Generated by Django 2.0.7 on 2018-08-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0011_sliderimage_long_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='text_color',
            field=models.CharField(default='000000', max_length=120),
        ),
    ]
