# Generated by Django 2.0.7 on 2018-08-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0012_sliderimage_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='fade_away',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='text_color',
            field=models.CharField(default='000000', help_text='Default = BLACK', max_length=120),
        ),
    ]
