# Generated by Django 2.0.7 on 2018-08-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0014_video_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='time_fade',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
