# Generated by Django 2.0.7 on 2018-08-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0015_video_time_fade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_bg_color', models.CharField(max_length=120)),
                ('nav_link_color', models.CharField(max_length=120)),
                ('name_color', models.CharField(max_length=120)),
                ('drop_bg_color', models.CharField(max_length=120)),
                ('drop_link_color', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='time_fade',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
