# Generated by Django 2.0.7 on 2018-08-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0017_style_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(editable=False, max_length=120),
        ),
    ]
