# Generated by Django 2.0.7 on 2018-08-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0018_auto_20180804_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='slider_interval',
            field=models.IntegerField(default=5000),
        ),
    ]
