# Generated by Django 2.0.7 on 2018-08-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0019_style_slider_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='auto_slider',
            field=models.BooleanField(default=True),
        ),
    ]
