# Generated by Django 2.0.7 on 2018-08-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0020_style_auto_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='auto_slider',
        ),
        migrations.RemoveField(
            model_name='style',
            name='slider_interval',
        ),
        migrations.AddField(
            model_name='slideradmin',
            name='auto_slider',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slideradmin',
            name='slider_interval',
            field=models.IntegerField(default=5000),
        ),
    ]
