# Generated by Django 2.0.7 on 2018-08-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0021_auto_20180807_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='x_text_pos',
            field=models.CharField(choices=[('c', 'Center'), ('l', 'Left'), ('r', 'Right')], default='c', max_length=120),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='y_text_pos',
            field=models.CharField(choices=[('c', 'Center'), ('t', 'Top'), ('b', 'Bottom')], default='c', max_length=120),
        ),
        migrations.AddField(
            model_name='video',
            name='x_text_pos',
            field=models.CharField(choices=[('c', 'Center'), ('l', 'Left'), ('r', 'Right')], default='c', max_length=120),
        ),
        migrations.AddField(
            model_name='video',
            name='y_text_pos',
            field=models.CharField(choices=[('c', 'Center'), ('t', 'Top'), ('b', 'Bottom')], default='c', max_length=120),
        ),
    ]
