# Generated by Django 2.0.7 on 2018-08-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0023_auto_20180807_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='x_text_pos',
            field=models.CharField(choices=[('center-align', 'Center'), ('left-align', 'Left'), ('right-align', 'Right')], default='center-align', max_length=120),
        ),
    ]
