# Generated by Django 2.0.7 on 2018-08-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0024_auto_20180807_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideradmin',
            name='slider_transition',
            field=models.IntegerField(default=500, help_text='Transition time between images'),
        ),
        migrations.AlterField(
            model_name='slideradmin',
            name='slider_interval',
            field=models.IntegerField(default=5000, help_text='Rate at which images change'),
        ),
    ]
