# Generated by Django 2.0.7 on 2018-08-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0025_auto_20180807_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slideradmin',
            old_name='slider_transition',
            new_name='transition_duration',
        ),
    ]
