# Generated by Django 2.0.7 on 2018-08-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0026_auto_20180807_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='mobile_icon_color',
            field=models.CharField(default='ffffff', max_length=120),
        ),
    ]
