# Generated by Django 2.0.7 on 2018-08-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0027_style_mobile_icon_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='text_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='text_es',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='text_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='text_es',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
