# Generated by Django 2.0.7 on 2018-08-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0028_auto_20180810_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
