# Generated by Django 2.0.7 on 2018-08-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0030_auto_20180811_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigonalStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='MainDiagonalAdmin', editable=False, max_length=120)),
                ('bg_effect', models.BooleanField()),
                ('main_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('main_img_bg_color', models.CharField(default='000000', max_length=120)),
                ('main_img_text_color', models.CharField(default='ffffff', max_length=120)),
                ('statement', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Diagonals Admin',
            },
        ),
        migrations.AlterModelOptions(
            name='style',
            options={'verbose_name': 'Landing Page Style'},
        ),
        migrations.RemoveField(
            model_name='style',
            name='main_img',
        ),
        migrations.RemoveField(
            model_name='style',
            name='main_img_bg_color',
        ),
        migrations.RemoveField(
            model_name='style',
            name='main_img_text_color',
        ),
    ]
