# Generated by Django 2.0.7 on 2018-08-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0033_auto_20180813_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digonalstyle',
            old_name='main_img_bg_color',
            new_name='first_sec_bg_color',
        ),
        migrations.RenameField(
            model_name='digonalstyle',
            old_name='main_img',
            new_name='first_sec_img',
        ),
        migrations.AlterField(
            model_name='digonalstyle',
            name='bg_effect',
            field=models.BooleanField(help_text="If set to True, the image won't be sized in order to achieve the effect"),
        ),
    ]
