# Generated by Django 2.0.7 on 2018-08-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0035_auto_20180813_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='digonalstyle',
            name='second_sec_text_color',
            field=models.CharField(default='ffffff', max_length=120),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='third_sec_text_color',
            field=models.CharField(default='ffffff', max_length=120),
        ),
    ]
