# Generated by Django 2.0.7 on 2018-08-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0036_auto_20180813_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digonalstyle',
            name='bg_effect',
        ),
        migrations.RemoveField(
            model_name='digonalstyle',
            name='first_sec_img',
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='second_sec_bg_effect',
            field=models.BooleanField(default=False, help_text="If set to True, the image won't be sized in order to achieve the effect"),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='third_sec_bg_effect',
            field=models.BooleanField(default=False, help_text="If set to True, the image won't be sized in order to achieve the effect"),
        ),
    ]
