# Generated by Django 2.0.7 on 2018-08-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0037_auto_20180815_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='digonalstyle',
            name='second_sec_img_side',
            field=models.CharField(choices=[('r', 'Right'), ('l', 'Left')], default='r', max_length=120),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='third_sec_img_side',
            field=models.CharField(choices=[('r', 'Right'), ('l', 'Left')], default='l', max_length=120),
        ),
    ]
