# Generated by Django 2.0.7 on 2018-08-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0038_auto_20180816_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='digonalstyle',
            name='second_sec_img_height',
            field=models.IntegerField(default=350),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='second_sec_img_width',
            field=models.IntegerField(default=250),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='third_sec_img_height',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='third_sec_img_width',
            field=models.IntegerField(default=300),
        ),
    ]
