# Generated by Django 2.0.7 on 2018-08-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0039_auto_20180816_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='digonalstyle',
            name='first_sec_height',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='second_sec_height',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='third_sec_height',
            field=models.IntegerField(default=350),
        ),
    ]
