# Generated by Django 2.0.7 on 2018-08-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0042_auto_20180830_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='digonalstyle',
            name='second_sec_title_en',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='second_sec_title_es',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='third_sec_title_en',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='third_sec_title_es',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
