# Generated by Django 2.0.7 on 2018-08-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0043_auto_20180830_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='digonalstyle',
            name='fourth_sec_bg_color',
            field=models.CharField(default='000000', max_length=120),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='fourth_sec_bg_effect',
            field=models.BooleanField(default=False, help_text="If set to True, the image won't be sized in order to achieve the effect"),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='fourth_sec_height',
            field=models.IntegerField(default=350),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='fourth_sec_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='fourth_sec_img_height',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='fourth_sec_img_side',
            field=models.CharField(choices=[('r', 'Right'), ('l', 'Left')], default='l', max_length=120),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='fourth_sec_img_width',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='fourth_sec_text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='fourth_sec_text_color',
            field=models.CharField(default='ffffff', max_length=120),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='fourth_sec_text_en',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='fourth_sec_text_es',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='fourth_sec_title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='fourth_sec_title_color',
            field=models.CharField(default='ffffff', max_length=120),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='fourth_sec_title_en',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='fourth_sec_title_es',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
