# Generated by Django 2.0.7 on 2018-09-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0044_auto_20180831_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digonalstyle',
            name='fourth_sec_bg_effect',
        ),
        migrations.RemoveField(
            model_name='digonalstyle',
            name='fourth_sec_img_side',
        ),
        migrations.RemoveField(
            model_name='digonalstyle',
            name='second_sec_bg_effect',
        ),
        migrations.RemoveField(
            model_name='digonalstyle',
            name='second_sec_img_side',
        ),
        migrations.RemoveField(
            model_name='digonalstyle',
            name='third_sec_bg_effect',
        ),
        migrations.RemoveField(
            model_name='digonalstyle',
            name='third_sec_img_side',
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='rounded_img',
            field=models.BooleanField(default=False),
        ),
    ]
