# Generated by Django 2.0.7 on 2018-09-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0045_auto_20180901_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digonalstyle',
            name='rounded_img',
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='fourth_sec_rounded_img',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='second_sec_rounded_img',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='digonalstyle',
            name='third_sec_rounded_img',
            field=models.BooleanField(default=False),
        ),
    ]
