# Generated by Django 2.0.7 on 2018-09-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0047_auto_20180902_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='digonalstyle',
            name='first_sec_mob_height',
            field=models.IntegerField(default=300),
        ),
    ]
