# Generated by Django 2.0.7 on 2018-09-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0048_digonalstyle_first_sec_mob_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='fade_away',
        ),
        migrations.RemoveField(
            model_name='video',
            name='show_text',
        ),
        migrations.RemoveField(
            model_name='video',
            name='text',
        ),
        migrations.RemoveField(
            model_name='video',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='video',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='video',
            name='text_es',
        ),
        migrations.RemoveField(
            model_name='video',
            name='time_fade',
        ),
        migrations.RemoveField(
            model_name='videoadmin',
            name='controls_on',
        ),
    ]
