# Generated by Django 2.0.7 on 2018-09-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0049_auto_20180904_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='button_color',
        ),
        migrations.RemoveField(
            model_name='video',
            name='play_pause_active',
        ),
        migrations.AddField(
            model_name='slideradmin',
            name='indicators_active_color',
            field=models.CharField(default='000000', help_text='Active bg color', max_length=120),
        ),
        migrations.AddField(
            model_name='slideradmin',
            name='indicators_color',
            field=models.CharField(default='ffffff', help_text='Non-active bg color', max_length=120),
        ),
    ]
