# Generated by Django 2.0.7 on 2018-09-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0050_auto_20180904_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='play_pause_active',
            field=models.BooleanField(default=True),
        ),
    ]
