# Generated by Django 2.0.7 on 2018-09-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0051_video_play_pause_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='button_color',
            field=models.CharField(default='ffffff', max_length=120),
        ),
    ]
