# Generated by Django 2.0.7 on 2018-09-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0052_video_button_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='diags_font_general',
            field=models.CharField(default='cursive', max_length=120),
        ),
        migrations.AddField(
            model_name='style',
            name='diags_font_name',
            field=models.CharField(default='Great+Vibes', max_length=120),
        ),
        migrations.AddField(
            model_name='style',
            name='name_font_general',
            field=models.CharField(default='cursive', max_length=120),
        ),
        migrations.AddField(
            model_name='style',
            name='name_font_name',
            field=models.CharField(default='Great+Vibes', help_text='+ symbol for spaces', max_length=120),
        ),
        migrations.AddField(
            model_name='style',
            name='statement_font_general',
            field=models.CharField(default='cursive', max_length=120),
        ),
        migrations.AddField(
            model_name='style',
            name='statement_font_name',
            field=models.CharField(default='Great+Vibes', max_length=120),
        ),
    ]
