# Generated by Django 2.0.7 on 2018-09-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaAdmin', '0053_auto_20180904_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='gallery_font_general',
            field=models.CharField(default='cursive', max_length=120),
        ),
        migrations.AddField(
            model_name='style',
            name='gallery_font_name',
            field=models.CharField(default='Great+Vibes', max_length=120),
        ),
    ]
