# Generated by Django 2.0.7 on 2018-07-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=120)),
                ('name', models.SlugField()),
                ('message', models.TextField()),
            ],
        ),
    ]
