# Generated by Django 2.0.7 on 2018-07-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='palo',
            field=models.CharField(choices=[('♥', 'Corazones'), ('♠', 'Picas'), ('♣', 'Treboles'), ('♦', 'Diamantes')], default='♥', max_length=120),
        ),
    ]
