# Generated by Django 2.0.7 on 2018-07-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0002_usercard_palo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='number',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='card',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
