# Generated by Django 2.0.7 on 2018-07-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0004_auto_20180719_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='card',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='name'),
        ),
    ]
