# Generated by Django 2.0.7 on 2018-07-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0005_auto_20180719_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='card',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='slug',
            field=models.SlugField(verbose_name='name'),
        ),
    ]
