# Generated by Django 2.0.7 on 2018-07-19 11:12

import Cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0006_auto_20180719_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='slug',
            field=models.SlugField(validators=[Cards.models.validate_name], verbose_name='name'),
        ),
    ]
