# Generated by Django 2.0.7 on 2018-07-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0007_auto_20180719_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
