# Generated by Django 2.0.7 on 2018-07-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0008_auto_20180719_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='slug',
            field=models.SlugField(verbose_name='name'),
        ),
    ]
