# Generated by Django 2.0.7 on 2018-08-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0009_auto_20180723_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='card',
            field=models.CharField(blank=True, editable=False, max_length=120, null=True),
        ),
    ]
